#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=18

start() {

	boardname=$(awk '/machine/ {print tolower($4)}' /proc/cpuinfo)

	case $boardname in
		'chowchow')
			ID=1
			;;
			*)
			ID=0
			;;
	esac

	MODE=`/sbin/uci get wireless.@wifi-iface[$ID].mode`
	SSID=`/sbin/uci get wireless.@wifi-iface[$ID].ssid`
	
	SSID_PREFIX=`/sbin/uci get wireless.@wifi-iface[$ID].ssid | sed s/-.*//`

	if [ "$SSID_PREFIX" != "Arduino" -a "$SSID_PREFIX" != "Linino" -a "$SSID_PREFIX" != "OpenWrt" ]
	then
		return
	fi
		
	PREFIX=$(awk '/machine/ {print $3}' /proc/cpuinfo)
		
	if [ "$MODE" == "ap" ]
	then
		SSID_SUFFIX=`/sbin/ifconfig wlan0 | /usr/bin/head -n 1 | /bin/grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' | /bin/sed 's/://g'`
		SSID=$PREFIX-$SSID_SUFFIX
		/sbin/uci "set" "wireless.@wifi-iface[$ID].ssid=$SSID"
		/sbin/uci commit wireless
		logger -t rename "WiFi renamed $SSID"
	fi
}
